services:
  database:
    image: postgres
    container_name: chi-pg
    restart: always
    ports:
      - 127.0.0.1:5432:5432 
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
